### ISSUE TITLE
Transparency doesn't work correctly in Texel 4x4 format

### ISSUE THREAD

**Issue by AntonioND** [Garhoogin/ptexconv#2]
It looks like 4x4 blocks that have transparent and solid pixels are converted correctly, but blocks with only transparent pixels are displayed as a solid color. This is the output I get:

![desmume-screenshot-0](https://github.com/Garhoogin/ptexconv/assets/6632664/95a14586-0ef9-4b4e-bd6f-4158d47d57cc)

This is my test project. You need ``ninja`` to build it, and BlocksDS (and Nitro Engine, and ptexconv installed in the ``BLOCKSDSEXT`` folder).

[sample.zip](https://github.com/Garhoogin/ptexconv/files/14002521/sample.zip)

**Comment by Garhoogin** [comment]
Should be fixed now as of the latest commit. Thanks for notifying me!
